// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  /**
   * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
   */
  interface GetMessageOptions {
    /**
     * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
     */
    escapeLt?: boolean
  }

  export interface WxtI18n extends I18n.Static {
    /**
     * The extension or app ID; you might use this string to construct URLs for resources inside the extension. Even non-localized extensions can use this message.
     * Note: You can't use this message in a manifest file.
     *
     * "<browser.runtime.id>"
     */
    getMessage(
      messageName: "@@extension_id",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "<browser.i18n.getUiLocale()>"
     */
    getMessage(
      messageName: "@@ui_locale",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * The text direction for the current locale, either "ltr" for left-to-right languages such as English or "rtl" for right-to-left languages such as Japanese.
     *
     * "<ltr|rtl>"
     */
    getMessage(
      messageName: "@@bidi_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "rtl"; otherwise, it's "ltr".
     *
     * "<rtl|ltr>"
     */
    getMessage(
      messageName: "@@bidi_reversed_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "left"; otherwise, it's "right".
     *
     * "<left|right>"
     */
    getMessage(
      messageName: "@@bidi_start_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "right"; otherwise, it's "left".
     *
     * "<right|left>"
     */
    getMessage(
      messageName: "@@bidi_end_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Speeding"
     */
    getMessage(
      messageName: "extName",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Auto-speed for every site — set once, never touch again. Works on YouTube, Udemy, Bilibili, Netflix & podcast players."
     */
    getMessage(
      messageName: "extDescription",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "No video detected"
     */
    getMessage(
      messageName: "noVideo",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Open a page with video to get started"
     */
    getMessage(
      messageName: "noVideoHint",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "$COUNT$ video detected"
     */
    getMessage(
      messageName: "videoDetected",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "$COUNT$ videos detected"
     */
    getMessage(
      messageName: "videosDetected",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "speed"
     */
    getMessage(
      messageName: "speedLabel",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "This site"
     */
    getMessage(
      messageName: "thisSite",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "All sites"
     */
    getMessage(
      messageName: "allSites",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Drag to adjust · $SPEED$×"
     */
    getMessage(
      messageName: "dragToAdjust",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Presets"
     */
    getMessage(
      messageName: "presets",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Custom"
     */
    getMessage(
      messageName: "custom",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "0.5 – 16"
     */
    getMessage(
      messageName: "speedPlaceholder",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Apply"
     */
    getMessage(
      messageName: "apply",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Range: $MIN$× – $MAX$× · Step: $STEP$×"
     */
    getMessage(
      messageName: "rangeStep",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Rate on Store"
     */
    getMessage(
      messageName: "rateOnStore",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    getMessage(
      messageName: "@@extension_id" | "@@ui_locale" | "@@bidi_dir" | "@@bidi_reversed_dir" | "@@bidi_start_edge" | "@@bidi_end_edge" | "extName" | "extDescription" | "noVideo" | "noVideoHint" | "videoDetected" | "videosDetected" | "speedLabel" | "thisSite" | "allSites" | "dragToAdjust" | "presets" | "custom" | "speedPlaceholder" | "apply" | "rangeStep" | "rateOnStore",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
  }
}
