// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  /**
   * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
   */
  interface GetMessageOptions {
    /**
     * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
     */
    escapeLt?: boolean
  }

  export interface WxtI18n extends I18n.Static {
    /**
     * The extension or app ID; you might use this string to construct URLs for resources inside the extension. Even non-localized extensions can use this message.
     * Note: You can't use this message in a manifest file.
     *
     * "<browser.runtime.id>"
     */
    getMessage(
      messageName: "@@extension_id",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "<browser.i18n.getUiLocale()>"
     */
    getMessage(
      messageName: "@@ui_locale",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * The text direction for the current locale, either "ltr" for left-to-right languages such as English or "rtl" for right-to-left languages such as Japanese.
     *
     * "<ltr|rtl>"
     */
    getMessage(
      messageName: "@@bidi_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "rtl"; otherwise, it's "ltr".
     *
     * "<rtl|ltr>"
     */
    getMessage(
      messageName: "@@bidi_reversed_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "left"; otherwise, it's "right".
     *
     * "<left|right>"
     */
    getMessage(
      messageName: "@@bidi_start_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "right"; otherwise, it's "left".
     *
     * "<right|left>"
     */
    getMessage(
      messageName: "@@bidi_end_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Speeding - Video Speed Controller"
     */
    getMessage(
      messageName: "extName",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Adjust video speed from 0.5× to 16× on any site. Works on YouTube, Bilibili, Netflix, Udemy, and more."
     */
    getMessage(
      messageName: "extDescription",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "No video detected"
     */
    getMessage(
      messageName: "noVideo",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Open a page with video to get started"
     */
    getMessage(
      messageName: "noVideoHint",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Try on YouTube"
     */
    getMessage(
      messageName: "noVideoCta",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "speed"
     */
    getMessage(
      messageName: "speedLabel",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "This site"
     */
    getMessage(
      messageName: "thisSite",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "All sites"
     */
    getMessage(
      messageName: "allSites",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Presets"
     */
    getMessage(
      messageName: "presets",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Custom"
     */
    getMessage(
      messageName: "custom",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "0.5 – 16"
     */
    getMessage(
      messageName: "speedPlaceholder",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Apply"
     */
    getMessage(
      messageName: "apply",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Rate on Store"
     */
    getMessage(
      messageName: "rateOnStore",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Alt+↑/↓ to adjust speed"
     */
    getMessage(
      messageName: "shortcutHint",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Loading speed settings"
     */
    getMessage(
      messageName: "ariaLoading",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Playback speed"
     */
    getMessage(
      messageName: "ariaSlider",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Custom speed value"
     */
    getMessage(
      messageName: "ariaCustomSpeed",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Apply custom speed"
     */
    getMessage(
      messageName: "ariaApplyCustom",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Rate on Chrome Web Store"
     */
    getMessage(
      messageName: "ariaRateOnStore",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Scenes"
     */
    getMessage(
      messageName: "scenes",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Course study"
     */
    getMessage(
      messageName: "sceneCourse",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Series bingeing"
     */
    getMessage(
      messageName: "sceneSeries",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Foreign listening"
     */
    getMessage(
      messageName: "sceneListening",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Add scene"
     */
    getMessage(
      messageName: "sceneAdd",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Edit"
     */
    getMessage(
      messageName: "sceneEdit",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Delete"
     */
    getMessage(
      messageName: "sceneDelete",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Save"
     */
    getMessage(
      messageName: "sceneSave",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Cancel"
     */
    getMessage(
      messageName: "sceneCancel",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Scene name"
     */
    getMessage(
      messageName: "sceneName",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Speed"
     */
    getMessage(
      messageName: "sceneSpeed",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "No scenes yet. Add one to get started."
     */
    getMessage(
      messageName: "sceneEmpty",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Add a scene"
     */
    getMessage(
      messageName: "ariaSceneAdd",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Scene name"
     */
    getMessage(
      messageName: "ariaSceneName",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Scene speed value"
     */
    getMessage(
      messageName: "ariaSceneSpeed",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "$COUNT$ video detected"
     */
    getMessage(
      messageName: "videoDetected",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "$COUNT$ videos detected"
     */
    getMessage(
      messageName: "videosDetected",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Drag to adjust · $SPEED$×"
     */
    getMessage(
      messageName: "dragToAdjust",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Range: $MIN$× – $MAX$× · Step: $STEP$×"
     */
    getMessage(
      messageName: "rangeStep",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Current speed $SPEED$×"
     */
    getMessage(
      messageName: "ariaSpeedDisplay",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Set speed to $SPEED$×"
     */
    getMessage(
      messageName: "ariaPresetSpeed",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Edit scene $NAME$"
     */
    getMessage(
      messageName: "ariaSceneEdit",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Delete scene $NAME$"
     */
    getMessage(
      messageName: "ariaSceneDelete",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Apply scene $NAME$ at $SPEED$×"
     */
    getMessage(
      messageName: "ariaSceneApply",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    getMessage(
      messageName: "@@extension_id" | "@@ui_locale" | "@@bidi_dir" | "@@bidi_reversed_dir" | "@@bidi_start_edge" | "@@bidi_end_edge" | "extName" | "extDescription" | "noVideo" | "noVideoHint" | "noVideoCta" | "speedLabel" | "thisSite" | "allSites" | "presets" | "custom" | "speedPlaceholder" | "apply" | "rateOnStore" | "shortcutHint" | "ariaLoading" | "ariaSlider" | "ariaCustomSpeed" | "ariaApplyCustom" | "ariaRateOnStore" | "scenes" | "sceneCourse" | "sceneSeries" | "sceneListening" | "sceneAdd" | "sceneEdit" | "sceneDelete" | "sceneSave" | "sceneCancel" | "sceneName" | "sceneSpeed" | "sceneEmpty" | "ariaSceneAdd" | "ariaSceneName" | "ariaSceneSpeed" | "videoDetected" | "videosDetected" | "dragToAdjust" | "rangeStep" | "ariaSpeedDisplay" | "ariaPresetSpeed" | "ariaSceneEdit" | "ariaSceneDelete" | "ariaSceneApply",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
  }
}
