// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/_locales/ar/messages.json"
    | "/_locales/da/messages.json"
    | "/_locales/de/messages.json"
    | "/_locales/en/messages.json"
    | "/_locales/es/messages.json"
    | "/_locales/fr/messages.json"
    | "/_locales/hi/messages.json"
    | "/_locales/it/messages.json"
    | "/_locales/ja/messages.json"
    | "/_locales/ko/messages.json"
    | "/_locales/nl/messages.json"
    | "/_locales/no/messages.json"
    | "/_locales/pt_PT/messages.json"
    | "/_locales/sv/messages.json"
    | "/_locales/zh_CN/messages.json"
    | "/_locales/zh_TW/messages.json"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/96.png"
    | "/icon/icon.svg"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
